### PR TITLE
Update installation guide

### PR DESCRIPTION
**Pull request by kevinthegreat1**
The guide needs to be updated since satin is added as a dependency.

### CODE REVIEW

**Comment by 0x3C50** [comment]
i don't see why this is necessary? the dependency is required regardless

**Comment by kevinthegreat1** [comment]
The current code in readme does not work anymore. You need to add either the repository block or exclude satin.

**Comment by 0x3C50** [comment]
even tho satin has been jij'd?

**Comment by kevinthegreat1** [comment]
Jij'ed mods can't be loaded by gradle as a dependency. Since gradle lists satin as a dependency in the pom file when building on jitpack, gradle tries to find satin when a mod imports renderer. Gradle can not find the jij'ed jar. However, in prod loader will load the jij jar and satin does not need to be downloaded separately. [Here](https://discord.com/channels/507304429255393322/592749519171616796/1131620257086324819) is a more detailed explanation on the fabric discord.

**Comment by 0x3C50** [comment]
i have changed the guide a bit, i don't think having the non-satin dependency is necessary. the library is loaded at runtime anyway, why exclude it?

**Comment by kevinthegreat1** [comment]
Imo it's an implementation detail and users shouldn't have to / might not want to add a repository.

**Pull request merged**
